### ISSUE TITLE
Error: Cannot find module 'rxjs/Observable/of'

### ISSUE THREAD

**Issue by psrcek** [nestjs/typescript-starter#39]
This error is displayed after running npm run start.
I followed the steps under "installation" at https://docs.nestjs.com/

the full error is as follows:

```
Error: Cannot find module 'rxjs/Observable/of'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:548:15)
    at Function.Module._resolveFilename (/home/david/git/nest/test/node_modules/tsconfig-paths/lib/register.js:31:40)
    at Function.Module._load (internal/modules/cjs/loader.js:475:25)
    at Module.require (internal/modules/cjs/loader.js:598:17)
    at require (internal/modules/cjs/helpers.js:11:18)
    at Object.<anonymous> (/home/david/git/nest/test/src/main.ts:7:1)
    at Module._compile (internal/modules/cjs/loader.js:654:30)
    at Module.m._compile (/home/david/git/nest/test/node_modules/ts-node/src/index.ts:422:23)
    at Module._extensions..js (internal/modules/cjs/loader.js:665:10)
    at Object.require.extensions.(anonymous function) [as .ts] (/home/david/git/nest/test/node_modules/ts-node/src/index.ts:425:12)
```

**Comment by kamilmysliwiec** [comment]
I guess you have installed `rxjs` 6.0.0 while latest stable Nest version is compatible with v5.x.x.

**Comment by Stivin** [comment]
Backwards compatibility package: `npm i --save rxjs-compat`
[learn more about the 5.5 to 6.0 migration](https://github.com/ReactiveX/rxjs/blob/master/MIGRATION.md)

**Comment by digiExaminer** [comment]
please run this command npm install --save rxjs-compat
